### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by abnerjacobsen** [Croydon/flask-xml-rpc-reloaded#8]
Hi,

I'm trying to use flask-xml-rpc-reloaded but got this error every time I call my Flaqsk app:

```
* Serving Flask app "main.py" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 287-775-524
192.168.64.1 - - [21/Nov/2018 21:17:18] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 325, in __call__
    self._flush_bg_loading_exception()
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 313, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 302, in _load_app
    self._load_unlocked()
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 242, in locate_app
    '\n\n{tb}'.format(name=module_name, tb=traceback.format_exc())
NoAppException: While importing "main", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/app/main.py", line 2, in <module>
    from flask_xmlrpcre import XMLRPCHandler, Fault
ImportError: cannot import name XMLRPCHandler
```

Testing using python colse got the same error:

```
# python
Python 2.7.15 (default, Oct 16 2018, 07:58:03) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask_xmlrpcre import XMLRPCHandler, Fault
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name XMLRPCHandler
```

Someone can help me in this issue ?

Regards,

**Comment by Croydon** [comment]
I believe this was a typo which got fixed in the meantime.
Could you please re-try with 0.1.4?

**Comment by Croydon** [comment]
@abnerjacobsen Ping

**Comment by ohlen1** [comment]
I am experiencing the same problem when trying to run a simple demo application. I'm using python3:
```
$ python3 --version
Python 3.7.3
```
Test code:
```
from flask import Flask, request
from flask_xmlrpcre import XMLRPCHandler, Fault

app = Flask(__name__)

handler = XMLRPCHandler('api')
handler.connect(app, '/api')

@handler.register
def hello(name="world"):
    if not name:
        raise Fault("unknown_recipient", "I need someone to greet!")
    return "Hello, %s!" % name

app.run()
```
Console output:
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from flask_xmlrpcre import XMLRPCHandler, Fault
ImportError: cannot import name 'XMLRPCHandler' from 'flask_xmlrpcre' (/my/pth/env/lib/python3.7/site-packages/flask_xmlrpcre/__init__.py)
```
@Croydon if there is a known workaround for this, I'd appreciate to know about it.

**Comment by abnerjacobsen** [comment]
@Croydon I left the project where your library was being tested, and I can not confirm they continue to use it and if the problem is solved.

Anyway, thanks for your feedback.

**Comment by Chiahung-Su** [comment]
Hi @Croydon I could not use the library under python 3.6 either.
```
$ pip3.6 freeze
Flask==0.10.1
Flask-XML-RPC-Re==0.1.4

$ python3.6 --version   
Python 3.6.8
```

Console output:
```
from flask_xmlrpcre import XMLRPCHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'XMLRPCHandler'
```

Please advice. Thanks.
